<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>4314ae44-7ea1-4bdc-bda3-c55826dd2434</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.RabbitMQ" />
        <PackageReference Include="Aspire.Hosting.Redis" />
        <PackageReference Include="Aspire.Hosting.SqlServer" />
        <PackageReference Include="Aspire.RabbitMQ.Client" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.Minio" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqlDatabaseProjects" />
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\API\API.csproj" />
        <ProjectReference Include="..\..\Database\DeliusRunningPictureDb\DeliusRunningPictureDb.sqlproj" />
        <ProjectReference Include="..\..\Database\DeliusStagingDb\DeliusStagingDb.sqlproj" />
        <ProjectReference Include="..\..\Database\MatchingDb\MatchingDb.sqlproj" />
        <ProjectReference Include="..\..\Meow\Meow.csproj" />
        <ProjectReference Include="..\..\Database\OfflocRunningPictureDb\OfflocRunningPictureDb.sqlproj" />
        <ProjectReference Include="..\..\Visualiser\Visualiser.csproj" />
        <ProjectReference Include="..\..\Database\AuditDb\AuditDb.sqlproj" />
        <ProjectReference Include="..\..\Database\OfflocStagingDb\OfflocStagingDb.sqlproj" />
		<ProjectReference Include="..\..\Database\ClusterDb\ClusterDb.sqlproj" />
		<ProjectReference Include="..\..\FakeDataSeeder\FakeDataSeeder.csproj" />
		<!-- DMS APPS -->
		<ProjectReference Include="..\..\Blocking\Blocking.csproj" />
		<ProjectReference Include="..\..\Cleanup\Cleanup.csproj" />
		<ProjectReference Include="..\..\DbInteractions\DbInteractions.csproj" />
		<ProjectReference Include="..\..\Delius.Parser\Delius.Parser.csproj" />
		<ProjectReference Include="..\..\FileSync\FileSync.csproj" />
		<ProjectReference Include="..\..\Import\Import.csproj" />
		<ProjectReference Include="..\..\Logging\Logging.csproj" />
		<ProjectReference Include="..\..\Matching.Engine\Matching.Engine.csproj" />
		<ProjectReference Include="..\..\Meow\Meow.csproj" />
		<ProjectReference Include="..\..\Offloc.Cleaner\Offloc.Cleaner.csproj" />
		<ProjectReference Include="..\..\Offloc.Parser\Offloc.Parser.csproj" />
    </ItemGroup>

</Project>
