name: Build Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --artifacts-path ./output

      - name: Upload build artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: build-outputs
          path: ./output/publish
          if-no-files-found: error