name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    name: Run linux tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Restore Dependencies (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet restore "$project"
          done
    
      - name: Build (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet build "$project" --configuration Release --no-restore
          done

      - name: Test (ubuntu)
        run: |
          for project in tests/**/*.csproj; do
            dotnet test "$project" --configuration Release --no-build
          done

  test-windows:
    name: Run windows tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet restore $_.FullName
          }
    
      - name: Build (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet build $_.FullName --configuration Release --no-restore
          }

      - name: Test (windows)
        run: |
          Get-ChildItem -Path tests -Filter *.csproj -Recurse | ForEach-Object {
            dotnet test $_.FullName --configuration Release --no-build
          }
